export const pricingPlans = [
  {
    name: "Essential Procurement",
    description: "Perfect for small teams getting started with digital procurement",
    pricemonthly: "$500",
    priceyearly: "$1000",
    features: [
      "Raise and manage purchase requests",
      "Track supplier compliance status",
      "Access up to 10 vendor profiles",
      "Basic approval flow",
      "Email notifications for key actions",
      "Affordable for small procurement teams",
    ],
    cta: "Start with Essentials →",
    popular: false,
  },
  {
    name: "Strategic Sourcing",
    description: "Designed for growing organizations focused on efficiency and compliance",
    pricemonthly: "$10",
    priceyearly: "$2000",
    period: "/month",
    features: [
      "Unlimited vendors & supplier onboarding",
      "Multi-step approval workflows",
      "RFP & quotation management",
      "Document storage & expiry alerts",
      "Role-based user access",
      "Audit trails and activity logs",
      "Enhanced visibility, reduced cycle times",
    ],
    cta: "Upgrade to Strategic Sourcing →",
    popular: true,
  },
  {
    name: "Enterprise Control",
    description: "For large teams with complex procurement needs and integrations",
    pricemonthly: "$20",
    priceyearly: "$5000",
    period: "/month",
    features: [
      "All Strategic features",
      "Integration with ERP & accounting systems",
      "Spend analytics dashboard",
      "Custom roles & permissions",
      "SLA-based support & dedicated success manager",
      "Full control across the supply chain",
    ],
    cta: "Talk to Sales →",
    popular: false,
  },
];
